export const STATES = Object.freeze({
  INTRO: 'INTRO', EXPLORING: 'EXPLORING', ARTIFACT_OPEN: 'ARTIFACT_OPEN',
  CLUE_REVEALED: 'CLUE_REVEALED', ARTIFACT_COLLECTED: 'ARTIFACT_COLLECTED',
  FINALE_UNLOCKED: 'FINALE_UNLOCKED', COMPLETE: 'COMPLETE'
});
